language: scala
scala:
   - 2.11.7

jdk:
  - oraclejdk8
  - openjdk7
  - openjdk6

sudo: false
cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2
before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

